### ISSUE TITLE
testing (discussion):  using patching or dependency injection in tests

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/parsers#15]
Code tested: <https://github.com/mini-kep/parsers/blob/master/parsers/getter/brent.py>

Note *brent.py*  has dependency injection at ```def yield_brent_dicts(download_func=fetch): ```

This should be used in designing the test for ```yield_brent_dicts()``` - need a mock fucntion to test ```yield_brent_dicts()```.

Same should be done in other getters.

**Comment by epogrebnyak** [comment]
This test actually does not do any dependency injection:
```
def test_yield_brent_dicts(mocker):
    mocker.patch('getter.brent.fetch', mock.MagicMock(return_value=None))
    mocker.patch('getter.brent.format_string', mock.MagicMock(return_value='2017-12-31'))
    mocker.patch('getter.brent.parse_response', mock.MagicMock(return_value=[['20171231', 2.23899]]))
    for data in brent.yield_brent_dicts():
        assert data == {'date': '2017-12-31', 'freq': 'd', 'name': 'BRENT', 'value': Decimal('2.2390')}
```

is just does heavy pathcing and kind of tests this part of loop, while shutting the fetch fucntion to None

```
 for row in parse_response(text):
        date = format_string(row[0])
        price = round(Decimal(float(row[1])), 4)
        yield {"date": date,
               "freq": "d",
               "name": "BRENT",
               "value": price}
```
also ```next()``` seems more appropriate than ```for``` .

Overall this soultion is no-go and has to be redesigned. We need:
- [ ] a mock function that has to be injected  ```yield_brent_dicts(download_func=mock_fetch)```
- [ ] a mock function is preferably designed outside the test
- [ ] the result is checked in ```next()```, not for 

Lets not do any other kind of work before this is done.

Other than this DI test need a list of other things to be tested in ```brent.py``` in words or plain code.

**Comment by JaroVojtek** [comment]
Hello Evgeny, see below my suggestion about test_brent.py

```python 

import pytest
from getter import brent
from decimal import Decimal

@pytest.fixture
def setup(monkeypatch):

    def fake_fetch(url):
        return "{\"series\":[{\"data\":[[\"20170925\",59.42]]}]}"

    monkeypatch.setattr(getter.brent, 'fetch' , fake_fetch)

def test_yield_brent_dict(setup):
    gen = getter.brent.yield_brent_dicts()
    next(gen)
```

**Comment by epogrebnyak** [comment]
Here is some good old lecture of testing and DI included <https://archive.org/details/pyvideo_310___tests-and-testability-188>

@JaroVojtek - your code is closer to dependency injection, but again I think it uses patching where you can simply pass a different arg to ```yield_brent_dicts```. Patching is probably good at some other places, here it seems excessive to me.

This is a fucntion to be injected:

```python 
 def fake_fetch(url):
        return "{\"series\":[{\"data\":[[\"20170925\",59.42]]}]}"
```
This is a test with DI:

```python
def test_yield_brent_dict():
    gen = getter.brent.yield_brent_dicts(download_func=fake_fetch)
    d = next(gen)
    assert d['value'] = 59.42
```

One can think of a fixture in the test, but the code above is good enough for me to put as an actual test.

**Comment by epogrebnyak** [comment]
Maybe the constant we can write without slashes
```python 
"""{"series":[{"data":[["20170925",59.42]]}]}""""
```

**Comment by epogrebnyak** [comment]
@JaroVojtek - if you can come up with some final edit for the test, lets integrate that with a PR

**Comment by JaroVojtek** [comment]
Hello Evgeny

Lets see final edit of the test below:

```
import pytest
from getter import brent
from decimal import Decimal

def fake_fetch(url):
    return """{"series":[{"data":[["20170925",59.42]]}]}"""

def test_yield_brent_dict():
    gen = getter.brent.yield_brent_dicts(download_func=fake_fetch)
    d = next(gen)
    assert d['date'] == '2017-09-25'
    assert d['value'] == Decimal('59.42')
```

**Comment by JaroVojtek** [comment]
Can i commit it to the project ? Thank you

**Comment by epogrebnyak** [comment]
@JaroVojtek - yes, lets' put that in!

**Comment by muroslav2909** [comment]
I am not sure that's is a good way create fake method outsidee the test. Thats why we use mocker. To patch everything that we want make fake call.
I want propose this way:

```python
from parsers.getter import brent
from decimal import Decimal
import mock

def test_yield_brent_dict():
    fake_fetch = mock.MagicMock(return_value="""{"series":[{"data":[["20170925",59.42]]}]}""")
    gen = brent.yield_brent_dicts(download_func=fake_fetch)
    d = next(gen)
    fake_fetch.assert_called_once()
    assert d['date'] == '2017-09-25'
    assert d['value'] == Decimal('59.42')
```

**Comment by epogrebnyak** [comment]
@muroslav2909, @JaroVojtek - I'll try to bring someone to give us advice on better practices in testing in this issue, meanwhile I'll:
- rename this issue as specific to mock/patching
- put another issue with origianl title

**Comment by JaroVojtek** [comment]
@muroslav2909 - Have you any underlined reason, why it is not good way to create fake methods outside the tests ?, or it is only your habit to not do that. In programming you still have more implementation ways how to reach your goal. But if you have some proven reason that is not good and it is not recommended, please share with us. In addition I am placing one very good articel about Unit Testing and there is also an example of creating fake object outside test - as dependency injection.

https://code.tutsplus.com/tutorials/write-professional-unit-tests-in-python--cms-25835

You can see example under Testing Errors Handling.

**Comment by muroslav2909** [comment]
@JaroVojtek Thanks for comment. I got  your arguments. Will use the way you recomended.

**Comment by JaroVojtek** [comment]
@muroslav2909 - You recomendations aren't bad aslo :). It is just another implementation way. Let's @epogrebnyak to make an decision.

**Comment by epogrebnyak** [comment]
I will try bring in one other person expert opinion here, so we can get qualified recoomendation. 

Meanwhile, just liked in a reading: 

> DI is very useful for two things:

>- it avoids surprises where your code is secretely relying on some object to exist somewhere
>- it allows test to be written that inject different sort of objects depending on the goal of that test 

Later on:

> ... you can use another fantastic, yet controversial, mechanism that dynamic languages offer: monkey patching. We will replace, at runtime, the requests module with an object we craft and can use in our test.

<https://stackoverflow.com/questions/11399148/how-to-mock-an-http-request-in-a-unit-testing-scenario-in-python>

My takaway is that if somethign can be tested with DI, test it with DI, if object is too complex/inaccessible - patch it.

**Comment by epogrebnyak** [comment]
```
#from mock import patch
-#
-# class MockingTestTestCase(unittest.TestCase):
-#
-#@patch('app.mocking.get_user_name')
-# def test_mock_stubs(self, test_patch):
-#test_patch.return_value = 'Mocked This Silly'
-#ret = test_method()
-#self.assertEqual(ret, 'Mocked This Silly'
```
