### ISSUE TITLE
should we round/beautify  349.89999999999998?

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/parsers#18]
RosstatKEP_* datatsets have quite many float numbers, most with long representation. Any common method to  round/beautify  values like ```349.89999999999998```?

**Comment by epogrebnyak** [comment]
The ```value```  seems to be immune to ```round(x)``` function. The output below was already rounded [here](https://github.com/mini-kep/parsers/blob/master/parsers/getter/kep.py#L39)

```
{'date': '1999-01-31',
 'freq': 'd',
 'name': 'CPI_FOOD_rog',
 'value': 110.40000000000001}
````

**Comment by esolovev** [comment]
https://stackoverflow.com/a/57704

We can continue to supply values like `110.40000000000001` and then use Python formatting to beautify it in the output.

**Comment by epogrebnyak** [comment]
> Could use decimal.Decimal instead of float, this has a different internal representation and shouldn't have these issues. https://stackoverflow.com/questions/19473770/how-to-avoid-floating-point-errors

> The issue is that in the float representation it is impossible to store exactly 5.2 for example, the binary representation of 5.2 is 101.0011001100110011... (infinite repeating) so can't store inside a float. Should either round just before printing or store inside some other datatype.

**Comment by epogrebnyak** [comment]
Now we run into this: ```TypeError: Object of type 'Decimal' is not JSON serializable```

**Comment by epogrebnyak** [comment]
Seems the issue is sorted out for now.
