### ISSUE TITLE
create the setup script

### ISSUE THREAD

**Issue by Rub4ek** [mini-kep/parsers#23]
Need a setup script so we can easily use it as a dependency.
Please create it or review this PR: https://github.com/mini-kep/parsers/pull/22

**Comment by epogrebnyak** [comment]
I merged a PR, but can we also exclude tests,py from codecov? This should also close  #16 - I closed this with d04d20c4b1240ccf700bd5b6d6c64346d05f624a

**Comment by epogrebnyak** [comment]
For for futher reference - we are running pytests like this now to gurantee PYTHONPATH is at right place

```
python -m pytest
```

**Comment by epogrebnyak** [comment]
@Rub4ek - can we close this now?
