### ISSUE TITLE
need cover getter.* modules 

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/parsers#28]
There are no tests for:
- [ ] brent.py
- [ ] cbr_fx.py
- [ ] kep.py

Ideally, need to keep tests simple/readable and closer to real, not imaginary risks in the program.

Also, best to keep in mind what tests are:
1. unittests that control functionality program structure
2. tests that validate functionality results 
3. integration/end-to-end test
4. regression/bug fixes

Everyone confortable with these ideas/defintions, @Andres-Unt, @muroslav2909 , @JaroVojtek?

**Comment by muroslav2909** [comment]
@epogrebnyak the tests for brent are finished here https://github.com/mini-kep/parsers/pull/27 . I am waiting for answer https://github.com/mini-kep/parsers/issues/15 how to go, and will make some edits in test_brew.py after it.

Now I'm working on test_cbr_fx, and will push a little bit later.

**Comment by JaroVojtek** [comment]
using pytest.raises seems to be better use for tests with exceptions handling, just my opinion

```
def test_format_string_with_bad_args():
    with pytest.raises(ValueError) as value_error:
        format_string('bad_date_format')
    assert "bad_date_format' does not match format '%Y%m%d'" in str(value_error.value)


def test_format_string_with_None_args():
    with pytest.raises(TypeError) as type_error:
        format_string(None)
    assert "strptime() argument 1 must be str, not None" in str(type_error.value)
```

**Comment by muroslav2909** [comment]
@JaroVojtek agree. looks much better

**Comment by JaroVojtek** [comment]
We can also assert if series_id is present in url

```
def test_make_url():
    key = "NOT_EIA_ACCESS_KEY"
    url = make_url(access_key=key)
    assert key in url
    assert 'PET.RBRTE.D' in url
```

**Comment by JaroVojtek** [comment]
Suggestion for test_fetch() with requests_mock library

```
import requests_mock
from parsers.config import EIA_ACCESS_KEY

def test_fetch(access_key=EIA_ACCESS_KEY):
    url = "http://api.eia.gov/series/?api_key="+access_key+"&series_id=PET.RBRTE.D"
    with requests_mock.mock() as m:
        m.get(url, text='fake response from url')
        assert fetch(url) == 'fake response from url'
```

**Comment by epogrebnyak** [comment]
What is mock_requests, where is it defined?

1 окт. 2017 г. 23:02 пользователь "Jaroslav Vojtek" <
notifications@github.com> написал:

**Comment by JaroVojtek** [comment]
Hi Evgeny,

requests_mock python package to mock out responses from requests package

https://pypi.python.org/pypi/requests-mock

Dňa 2. 10. 2017 12:40 dopoludnia používateľ "Evgeny Pogrebnyak" <
notifications@github.com> napísal:

**Comment by JaroVojtek** [comment]
I have tried also to mock fetch() using decorator. but its not working in this way, It has to be done as pytest.fixture

```
@requests_mock.mock()
def test_fetch2(m, access_key=EIA_ACCESS_KEY):
    url = "http://api.eia.gov/series/?api_key="+access_key+"&series_id=PET.RBRTE.D" 
    m.get(url, text='data')
    assert fetch(url) == 'data'
```

  @requests_mock.mock()
  def test_fetch2(m, access_key=EIA_ACCESS_KEY):
E       fixture 'm' not found
>       available fixtures: cache, capfd, capsys, doctest_namespace, metadata, monkeypatch, pytestconfig, record_xml_property, recwarn, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
