### ISSUE TITLE
new CBR_USD parser class

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/parsers#4]
- [x] make CBR_USD(Parser) class in definitions.py
- [x] add some new attributes to CBR_USD and RosstatKEP
- [x] (optionally) add mock output to CBR_USD in get_data()
- [x] generate two md tables for CBR_USD and RosstatKEP

Time: 1-2h.

**Comment by kkravchuk** [comment]
Изменения в pull request.
Примечания:
1. Я сделал метод get_data в CBR_USD по образцу класса RosstatKEP, но вероятно он должен принимать даты в виде параметров.
2. Возможно, вместо float для значений валютного курса лучше использовать типы чисел с фиксированной точностью, например, decimal.Decimal или gmpy.mpf.
3. Насколько я понял, данные по курсу доллара на сайте ЦБ РФ есть с 1 июля 1992 года, сначала курс устанавливался с периодичностью раз в 2-7 дней, а с 17 мая 1996 года - ежедневно (во вторник-субботу).
4. Не добавил атрибут periodicity в RosstatKEP и CBR_USD, поскольку, похоже, он дублирует атрибут freq.
5. Возможно, assert нужно заменить на юнит-тесты?

**Comment by epogrebnyak** [comment]
Спасибо за предложения/идеи:
1. пока этот метод - мок/заглушка, по идее он должен принимать все параметры из инита класса (круг переменных, ограниченния натдату и заданную частоту)
2. Для прототипа оставим float, потом вернёмся - там точность 4 знака после запятой, что нам дадут другие типы? С типами кстати будет проблема с датой, она пока строка, но где-то должна переходить в другой тип, возможно на уровне БД
Остальное позже

**Comment by kkravchuk** [comment]
Таблицы:

| Parameter | Value |
| --------- | ----- |
| Job | Parse sections of KEP Rosstat publication |
| Variables | CPI_rog, RUR_EUR_eop |
| Frequency | aqm |
| Last updated | NA |
| Expected update | NA |
| Source URL | http://www.gks.ru/wps/wcm/connect/rosstat_main/rosstat/ru/statistics/publications/catalog/doc_1140080765391 |
| Source type | Word |

| Parameter | Value |
| --------- | ----- |
| Job | Retrieve the official USD to RUB exchange rate from the Bank of Russia public API |
| Variables | CBR_USD |
| Frequency | d |
| Last updated | NA |
| Expected update | NA |
| Source URL | http://www.cbr.ru/scripts/Root.asp?PrtId=SXML |
| Source type | API |

**Comment by kkravchuk** [comment]
По поводу float: насколько я понимаю, особенность этого типа в том, что вместо 0.3 может появиться, например, 0.30000000000000004. 
Кстати, свои числовые типы есть и у numpy, например numpy.float64.

**Comment by epogrebnyak** [comment]
С лишними знаками в float проблема известная, я пока ее решаю округлением по значимых разрядов перед записью в выходные значения.

**Comment by epogrebnyak** [comment]
| Parameter | Value |
| --------- | ----- |
| Source | Source URL |
| Source type | Word |
| Frequency | aqm |
| Variables | CPI_rog, RUR_EUR_eop |

**Comment by epogrebnyak** [comment]
'| Parser | RosstatKEP |\n| ------ | ---------- |\n| Source | Sections of KEP Rosstat publication |\n| URL | [http://www.gks.ru/wp](http://www.gks.ru/wps/wcm/connect/rosstat_main/rosstat/ru/statistics/publications/catalog/doc_1140080765391) |\n| Source type | Word |\n| Frequency | aqm |\n| Variables | CPI_rog, RUR_EUR_eop |'

**Comment by epogrebnyak** [comment]
| Parser | RosstatKEP |
| ------ | ---------- |
| Description | Parse sections of KEP Rosstat publication |
| URL | [http://www.gks.ru/wps/wcm/connect/rosstat_main/rosstat/ru/st...](http://www.gks.ru/wps/wcm/connect/rosstat_main/rosstat/ru/statistics/publications/catalog/doc_1140080765391) |
| Source type | Word |
| Frequency | Annual, quarterly, monthly |
| Variables | CPI_rog, RUR_EUR_eop |


| Parser | CBR_USD |
| ------ | ------- |
| Description | Retrieve Bank of Russia official USD to RUB exchange rate |
| URL | [http://www.cbr.ru/scripts/Root.asp?PrtId=SXML](http://www.cbr.ru/scripts/Root.asp?PrtId=SXML) |
| Source type | API |
| Frequency | Daily |
| Variables | CBR_USD |

**Comment by epogrebnyak** [comment]
> Насколько я понял, данные по курсу доллара на сайте ЦБ РФ есть с 1 июля 1992 года, сначала 
> курс устанавливался с периодичностью раз в 2-7 дней, а с 17 мая 1996 года - ежедневно (во вторник-субботу).

Сейчас курс ЦБ это курс фиксинг на бирже предыдущий день, поэтому он устанавливается пн на вторник и т.д., можно это данные передвинуть + отпарсить сам курс фиксинга c сайта Московской биржи для контроля.

> Не добавил атрибут periodicity в RosstatKEP и CBR_USD, поскольку, похоже, он дублирует атрибут freq.

Я также поработал над уменьшением количества переменных, всякие полезные, но пока отсутствующие даты убрал

> Возможно, assert нужно заменить на юнит-тесты?
да, нужно перенести assert  в тесты, единственное - не уверен что тесты на конкретное значение должны проходить, я думаю тест должен проверять тип результата и наличие значений в нем.


Из нужного еще (1ч?): 
- [ ] давайте еще один класс сделаем для нефти Брент (есть в списке на первой странице)
- [ ] переименуем definitions в parser
- [ ] перенесем assert  в pytest

После этого подключу travis/coverage + займемся методом get_data.

Get_data  в одном случае будет считывать данные из стабильного URL репозитария, а в двух других - вызывать парсеры, код которых видимо надо переносить в этот репозитарий. 

С парсерами мне пока не нравится:
- kep выдает результат в виде csv, нужно менять на json по точкам
- нужно кешировать результаты парсинга, чтобы не напрягать API
- там где мои личные ключи для API - убирать из репо в локальный файл
