### ISSUE TITLE
add database upload methods

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/parsers#40]
See TODO in ```ParserBase.upload()``` and ```Dataset.upload()```

**Comment by epogrebnyak** [comment]
@SuperVasya?

**Comment by eskarimov** [comment]
@epogrebnyak Did I get it right that gen = self.yield_dicts() and gen = Dataset.yield_dicts(start, end) return data which has to be uploaded?
Should I use environment variables like `UPLOAD_URL` to avoid hardcoded URL?

**Comment by epogrebnyak** [comment]
> Should I use environment variables like UPLOAD_URL to avoid hardcoded URL?
lets do hardcoded vars first, as parsers do not have an env of their own
