### ISSUE TITLE
Evaluate scheduler options

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/parsers#42]
По поводу шедулера - есть два варианта https://devcenter.heroku.com/articles/scheduler и https://devcenter.heroku.com/articles/clock-processes-python

1. Просто шедулер. Запуск строго или каждые 10 минут, или каждый час, или каждый день. По сути команда heroku run ... В нашем случае это heroku run python <parser_name>. Вопрос - команды запуска шедулеров тогда в один файл класть или по файлам раскидывать и столько же шедулеров создавать?

2. APS Scheduler. Создаётся процесс типа clock в Heroku, запускается файл с расписанием, когда какой парсер дёргать. Для описания используется python библиотека APSScheduler. Плюс в том, что можно более гибко настроить расписание

**Comment by epogrebnyak** [comment]
Я правильно понимаю, что нам проще начать с heroku run? 
И для репо parsers нужен свой dyno?

**Comment by epogrebnyak** [comment]
Насчет очередей задач первое что приходит на ум - записывать ежедневно результаты Brent и cbr_fx, потом добавить ust,  когда ust будет готов

**Comment by eskarimov** [comment]
@epogrebnyak да, проще начать с heroku run. Для парсеров лучше отдельный проект создать, чтобы также всё обновлялось автоматически с Гитхаба

**Comment by epogrebnyak** [comment]
Не очень понял 'создать отдельный проект' - у нас же уже отдельный. Или
что-то поменять надо?

**Comment by eskarimov** [comment]
@epogrebnyak у нас сейчас работает одно приложение с базой данных. Обновляется из репо db, про парсеры ничего не знает. Для парсеров отдельное приложение надо заводить или как-то объединить вместе db и parsers

**Comment by epogrebnyak** [comment]
Понял, "проект" = приложение в heroku, можете сделать и потом мне оттрансферить?

**Comment by epogrebnyak** [comment]
Closing in favour of #43
