### ISSUE TITLE
tests class for upload_to_database()

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/parsers#44]
[tests class for upload_to_database()](https://github.com/mini-kep/parsers/blob/master/parsers/tests/test_uploader.py#L29-L33):
- write in comments what scenarios you suggest to test 
- write in comments how you plan to test for it, eg. actual call or some mocking
- time permititng, implement some or all proposals in actual test code 

pls remember the [testing guidelines](https://github.com/mini-kep/intro/tree/master/testing_guidelines)

**Comment by bhumkong** [comment]
In the test, I would create a mock `to_json` function: `def to_json(gen): return gen`
and test `upload_to_database` on a predefined list of correct JSON strings by passing them as `gen` parameter.
I'd then create mock `requests.post` to assert that `url == endpoint`. So, I define `TEST_URL="test_url_value"`, define `requests.post` function that asserts `url == TEST_URL`, then call `upload_to_database` with `endpoint=TEST_URL`. If assertion is successfull, our `requests.post` function returns an object of mock class with attribute `status_code=200`.
The same for checking the `token` argument. And maybe for `gen`/`data` too.

**Comment by epogrebnyak** [comment]
Code under test: 
```
def upload_to_database(gen, endpoint=UPLOAD_URL, token=UPLOAD_API_TOKEN):
    """Save data from generator *gen* to database endpoint.
        Returns:
            True on success (status code 200),
            False otherwise
        """
    _data = to_json(gen)
    response = requests.post(url=endpoint,
                             data=_data,                             
                             headers={'API_TOKEN': token})
    if response.status_code == 200:
        return True
    else:
        return False
```

**Comment by epogrebnyak** [comment]
>In the test, I would create a mock to_json function: def to_json(gen): return gen
>and test upload_to_database on a predefined list of correct JSON strings by passing them as gen 
> parameter.

Maybe we are better off just testing the ```to_json()``` function, no mock.

**Comment by epogrebnyak** [comment]
>I'd then create mock requests.post to assert that url == endpoint. So, I define TEST_URL="test_url_value", define requests.post function that asserts url == TEST_URL, then call upload_to_database with endpoint=TEST_URL. If assertion is successfull, our requests.post function returns an object of mock class with attribute status_code=200.

mocking is really the only way to do a network response, but some would say it is a bit of waste of time as we are both creating and testing for the same thing. anyways the network part is now the ```post()``` function, it can be tested with mock, but I'd put that on hold.
