### ISSUE TITLE
upload fails on large datasets

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/parsers#48]
```python 
from parsers.runner import CBR_USD

# this will pass
assert CBR_USD('2017-01-01').upload()

# this will fail
assert CBR_USD().upload()
```

**Comment by epogrebnyak** [comment]
```CBR_USD()``` is equivalent to ```CBR_USD('1992-01-01)```

**Comment by bhumkong** [comment]
I couldn't reliably reproduce it.
Maybe the problem is on the server side due to large JSON.

**Comment by bhumkong** [comment]
Generated JSON is valid.

**Comment by bhumkong** [comment]
And, you mean `from parsers.runner import CBR_USD`, right?

**Comment by epogrebnyak** [comment]
Updated code, thanks! So the second statement passes on you? 

We can leave it as it is now, but my next thought is what is json file size for this? My suspicion it does get processed by server anyways, but it takes too ling snd the flask view returns 400 status.

**Comment by epogrebnyak** [comment]
Maybe need to read from uploaded data from db in order to verify it was uploaded. Reading must be done with pausing, as it will clog the application.

**Comment by bhumkong** [comment]
Sounds like a dirty hack.

**Comment by epogrebnyak** [comment]
@bhumkong bhumkong - what exactly is dirty about it? what are better solutions?

**Comment by bhumkong** [comment]
We know that upload sometimes works incorrect and instead of fixing it we download the data back and check if it is correct. That is dirty.

**Comment by bhumkong** [comment]
I'm not saying I have a solution, but what you propose doesn't really seem like one to me.
Maybe as a temporary workaround.

**Comment by epogrebnyak** [comment]
>We know that upload sometimes works incorrect and instead of fixing it we download the data back and check if it is correct. That is dirty.

Not sure I understand your point. The upload fails of concurrency - too much work not processed by the server. There has to be a stop before work is finished.

**Comment by bhumkong** [comment]
If the server fails to process a request, it should at least inform the client about it.
