### ISSUE TITLE
separate test suite to local and web call tests

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/parsers#73]
What are pytest capabilities to run a specific group of tests?  

Review <http://pytest.readthedocs.io/en/reorganize-docs/new-docs/user/pytestmark.html> + provide example how we can run:

- all local tests
- all webtests
- both

**Comment by epogrebnyak** [comment]
```pytest -m "not webtest"``` will run tests except decorated with ```webtest```

**Comment by Perevedko** [comment]
https://github.com/mini-kep/parsers/commit/5f31de8a4d2c617a65923fe194d5e95258b2dd22
