### ISSUE TITLE
lists the parsers with/without actual API or static files call within the tests

### ISSUE THREAD

**Issue by oliaboo** [mini-kep/parsers#84]

**Comment by epogrebnyak** [comment]
API or static file call

**Comment by oliaboo** [comment]
Parsers with actual API or static files call:
- parsers/getter/tests/test_ust.py (extracting web pages response)
- parsers/getter/tests/test_kep.py (reading csv file)

Parsers without API call:
- parsers/getter/tests/test_cbr_fx.p
- parsers/getter/tests/test_base.py
- parsers/getter/tests/test_brent.py

**Comment by epogrebnyak** [comment]
A parser is actually only the classes in getter folder, also listed in PARSERS constant.

**Comment by epogrebnyak** [comment]
@oliaboo - can you update the listing?

**Comment by oliaboo** [comment]
yes, sure.
I thought, that this was about all the tests within repo

**Comment by oliaboo** [comment]
Parsers with actual API or static files call:
- parsers/getter/tests/test_ust.py (extracting web pages response)
  test_UST_on_real_call() -> calling extract method of ParserBase
  test_UST_on_randomised_year_reads_whole_year_data() -> calling extract() method of ParserBase (skipped with pytest.mark.skip)
- parsers/getter/tests/test_kep.py (reading csv file)
  test_get_dataframe_from_repo_on_real_data() -> calling read_csv() function of kep module

Parsers without API call:
- parsers/getter/tests/test_cbr_fx.py
  test_get_cbr_er() -> calling extract method of ParserBase with FakeScrapper class
- parsers/getter/tests/test_brent.py
  test_parse_response() -> response text returned by fake_fetch()
  test_yield_brent_dict() -> response text returned by fake_fetch()

**Comment by epogrebnyak** [comment]
TODO:
- [x] add `by_web_call` or similar line into tests that access web - the intent is to make naming of web distinct
- [x] add decorator `@pytest.mark.webtest` to web tests

I think we should exclude `parsers/getter/tests/test_base.py` from listing of no-API tests, becuase it is not intended for web call.

**Comment by oliaboo** [comment]
1. by_web_call added with #85 
2. I've checked, and the decorator is already in tests/
3. test_base removed from the list

**Comment by epogrebnyak** [comment]
Seems fine now!
